/**
* Constants used in Redux.
*/

//GET Equipment Info
export const REQUEST_GET_EQUIPMENT_INFO = 'REQUEST_GET_EQUIPMENT_INFO';
export const RECEIVE_GET_EQUIPMENT_INFO = 'RECEIVE_GET_EQUIPMENT_INFO';

//SET Equipment Info
export const REQUEST_SET_EQUIPMENT_INDEX = 'REQUEST_SET_EQUIPMENT_INDEX';
export const RECEIVE_SET_EQUIPMENT_INDEX = 'RECEIVE_SET_EQUIPMENT_INDEX';